import Heading from "@containers/Heading/Heading";
import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="color-scheme" content="dark" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Heading label="Zacznij estymować szybciej i trafniej" />
      </header>
    </div>
  );
};

export default Home;
